travis:
  secure:
    BINSTAR_TOKEN: cl1rmEVomq5Wk4KU2siiyu1gAZSeLbCU7KHqoUFxpiNodfALn4+FxqQ3ROkbd8nIQpBoMBx7y9Q+IaWx0oOj75z1Z17GK4hYCMUz7nEI9F6PaIVdFlOrf8lkNztMZH8bKXTiM6os85SXZxVau52KUmvXRUwarZOSPE93YaAOjMyTEFGTGrgh+LJA77gsMrdndvgQneoOR3Mhw4CbBKcJDxGfxWu9D1bZmDov/AB+x9xnAMQRXy4p7Ji/195HtsxZIYkkOq4fJ5cnG1Rk1ojZL6tehsMDACGCJTpk89cToe0wh4LbjipKtXEKt5YNndQlSid+NjsGpkfslkzREB9WBsL33D3qxYVXVF4jS8SEdB09CA2iYWoUiKz1nqQW85o+p46+HcL/iAyjN84rCuUGBYNe5it6eIefQxL/qxqLsPowCcoAbjtFKf2jymMBQZfWRaxD4uUruIGhHWqqYjxJ0IwTdU1bgvEei5U3L9SOczO5tuLxIQiTisDUruOEW3ywE1lfiyKyBnuKbHpuLeybF/cvzrzW5jAyIfPxUkHAYGcU8h57tKPHa6DXidNUJzfSIkNxKPgxSECsm2khp4py/ayM3Cl7TtjV5Pz/FikvnP/RXP8+gMUNrxN9lXC5UdN+1VBtWyDX0tZsYyWgd03cMA46muwswZZz/O13U1o9eKg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
